In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [2]:
"Data"+" Analysis"

'Data Analysis'

In [5]:
df1 = df[["Name", "Sex", "Age"]][0:5]

In [7]:
df1

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [8]:
df2 = df[["Name", "Sex", "Age"]][5:10]
df2

                                                Name     Sex   Age
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [ ]:
pd.concat([df1, df2], axis = 0) #concatenate pandas dataframe/object along a particular axis
#by default axis 0, means the dataframes will be concatnated row wise(appears to be vertical)
#concatenation means keeping two dataframes eithe rhorizontally or vertically
# here 0 to 4 is a df1 and 5 to 9 is df2.

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [ ]:
pd.concat([df1, df2], axis = 1) # in column getting df1 and df2.

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [ ]:
df2.reset_index(drop = True, inplace = True) # remove nul value
df2

                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                     Palsson, Master. Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [13]:
df1

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [14]:
pd.concat([df1, df2], axis = 1) # in column getting df1 and df2.

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,"Moran, Mr. James",male,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,"McCarthy, Mr. Timothy J",male,54.0
2,"Heikkinen, Miss. Laina",female,26.0,"Palsson, Master. Gosta Leonard",male,2.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
4,"Allen, Mr. William Henry",male,35.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

## Merge/ join 2 dataframes  
1. Inner Merge: If you are merging base on common element is called inner merge(intersection)  
2. Left Merge: Whaterever there is on dataframe A base on that you are merging is called left merge  
3. Right Merge: Based on All elements on right dataframe B are merge is called right merge 
4. Outer Merge: all the common element of the common column from both the dataframe will be printed.
5. Cross Merge: complete merge of all the dataframes. outer merge. is called cross merge.    Every permutation of rows are there

In [15]:
#merge
df1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]
})
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [18]:
df2 =  pd.DataFrame({'key1':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
}
)
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [ ]:
pd.merge(df1, df2, how = "inner") # here key1 is common column in both and 1, 2, 6 values of key 1 column is same

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [ ]:
pd.merge(df1, df2, how = 'left') # all the values of df1 is printed and common values are 1, 2, 6 are there and rest are NA

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [20]:
pd.merge(df1, df2, how = 'right') # all the values of df2 is printed and common values are 1, 2, 6 are there and rest are NA

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [21]:
pd.merge(df1, df2, how = "outer") #all the common element of the common column will be printed and common values are 1, 2, 6 are there and rest are NA

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [22]:
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [23]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [24]:
pd.merge(df1, df2, how = "cross") # each row of df1 will be repeated for all rows of df2. i.e. row 1 of df2 is repeated 5 times for 5 rows of df2

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [25]:
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [26]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [28]:
pd.merge(df1, df2, how = 'left', left_on="key2", right_on="key4") # in this takes common values from key2 from df1 and key 4 from df2. i.e. 5,6,7,8 are common in both key2 and key4
# and science key1 we are taking common even though it is, so another key1 for df2 is created as its not common

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     3     NaN   NaN   NaN
1       2     5     4     2.0   5.0  56.0
2       4     6     5    45.0   6.0   5.0
3       5     7     6     6.0   7.0   6.0
4       6     8     6    67.0   8.0   6.0

## join >> join works based on index/merge works based on columns

In [29]:
df1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]},
                    index = ['a', 'b', 'c', 'd', 'e']
)

In [30]:
df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [31]:
df2 =  pd.DataFrame({'key6':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
},
index = ['a', 'b', 'h', 'i', 'j']
)
df2

   key6  key4  key5
a     1    56     3
b     2     5    56
h    45     6     5
i     6     7     6
j    67     8     6

In [ ]:
df1.join(df2, how = "inner") #joins columns of another dataframe based on common index
# here a and b index are common in both df

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [ ]:
df1.join(df2, how = "left") #all elements of df1 printed and common index of values from both dfs i.e. a, b remainng are NA

   key1  key2  key3  key6  key4  key5
a     1     4     3   1.0  56.0   3.0
b     2     5     4   2.0   5.0  56.0
c     4     6     5   NaN   NaN   NaN
d     5     7     6   NaN   NaN   NaN
e     6     8     6   NaN   NaN   NaN

In [ ]:
df1.join(df2, how = "right") # all elements of df2 printed and common index of values from both dfs i.e. a, b remainng are NA

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0     1    56     3
b   2.0   5.0   4.0     2     5    56
h   NaN   NaN   NaN    45     6     5
i   NaN   NaN   NaN     6     7     6
j   NaN   NaN   NaN    67     8     6

In [ ]:
df1.join(df2, how = "outer") # printed coomoun indexes and common values, remaining are NA

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0   1.0  56.0   3.0
b   2.0   5.0   4.0   2.0   5.0  56.0
c   4.0   6.0   5.0   NaN   NaN   NaN
d   5.0   7.0   6.0   NaN   NaN   NaN
e   6.0   8.0   6.0   NaN   NaN   NaN
h   NaN   NaN   NaN  45.0   6.0   5.0
i   NaN   NaN   NaN   6.0   7.0   6.0
j   NaN   NaN   NaN  67.0   8.0   6.0

In [36]:
df1.join(df2, how = "cross") # each row of df1 will be repeated 5 times for 5 rows of df2

    key1  key2  key3  key6  key4  key5
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    67     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    67     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    67     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    67     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    67     8     6

In [37]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## apply>> to apply a function on all the elements/values of a column

In [38]:
df["Fare_inr"] = df['Fare'].apply(lambda x: x*90)

In [39]:
df["Fare_inr"]

0       652.500
1      6415.497
2       713.250
3      4779.000
4       724.500
         ...
886    1170.000
887    2700.000
888    2110.500
889    2700.000
890     697.500
Name: Fare_inr, Length: 891, dtype: float64

In [ ]:
df #in df also fare_inr column is added

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500

In [41]:
len("Ram")

3

In [42]:
df["Name"].apply(len)

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [43]:
df["Name_len"] = df["Name"].apply(len)

In [44]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19

In [45]:
#user defined function inside apply
def convert(x):
    return x*90

In [46]:
df["Fare1"] = df["Fare"].apply(convert)

In [47]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1170.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2700.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,2110.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2700.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,697.500

In [48]:
def create_flag(x):
    if x < 10:
        return "cheap"
    if x>=10 and x<20:
        return "medium"
    else:
        return "high"

In [49]:
create_flag(21)

'high'

In [50]:
df["flag_fare"] = df['Fare'].apply(create_flag)

In [51]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare1,flag_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500,cheap
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250,cheap
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1170.000,medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2700.000,high
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,2110.500,high
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2700.000,high
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,697.500,cheap

In [52]:
data = {"a": [1, 2, 3, 4],
       "b": [5, 5, 6, 7],
       "c": ["pw", "skills", "aj", "cj"]}
df1 = pd.DataFrame(data)

In [53]:
df1

   a  b       c
0  1  5      pw
1  2  5  skills
2  3  6      aj
3  4  7      cj

In [ ]:
df1.set_index('c', inplace = True) #set column c as a index

In [55]:
df1

        a  b
c
pw      1  5
skills  2  5
aj      3  6
cj      4  7

In [56]:
df1.reset_index(drop = True, inplace = True)

In [57]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [58]:
df1.reindex([1, 2, 3, 0]) #makes new index for series and dataframe

   a  b
1  2  5
2  3  6
3  4  7
0  1  5

In [59]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [60]:
for i in df1.iterrows(): #row wise
    print(i, "......")

(0, a    1
b    5
Name: 0, dtype: int64) ......
(1, a    2
b    5
Name: 1, dtype: int64) ......
(2, a    3
b    6
Name: 2, dtype: int64) ......
(3, a    4
b    7
Name: 3, dtype: int64) ......

In [61]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [62]:
for i in df1.items(): #column wise
    print(i)

('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64)
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64)

In [63]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [64]:
def func_sum(x):
    return x.sum()

In [ ]:
df1.apply(func_sum, axis = 0)  #column wise sum of a and b column

a    10
b    23
dtype: int64

In [66]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [ ]:
df1.apply(func_sum, axis = 1) # first sum rows and then total value

0     6
1     7
2     9
3    11
dtype: int64